//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN
    {
        public BAN()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int MABAN { get; set; }
        public string MAKV { get; set; }
        public string TENBAN { get; set; }
        public string TINHTRANG { get; set; }
    
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual KHUVUC KHUVUC { get; set; }
    }
}
