//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGNHAP
    {
        public string TENDN { get; set; }
        public string MK { get; set; }
        public string EMAIL { get; set; }
        public string QUYEN { get; set; }
    }
}
