//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public int MAHD { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<int> MABAN { get; set; }
        public Nullable<System.DateTime> NGAYXUATHOADON { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
