//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_THUC_UONG
    {
        public LOAI_THUC_UONG()
        {
            this.THUC_UONG = new HashSet<THUC_UONG>();
        }
    
        public int MALOAI { get; set; }
        public string TENLOAI { get; set; }
        public string MOTA { get; set; }
    
        public virtual ICollection<THUC_UONG> THUC_UONG { get; set; }
    }
}
