//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCF_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUC_UONG
    {
        public THUC_UONG()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public int MA_THUC_UONG { get; set; }
        public int MALOAI { get; set; }
        public string TEN_THUC_UONG { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string HINHANH { get; set; }
        public Nullable<decimal> GIA { get; set; }
    
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual LOAI_THUC_UONG LOAI_THUC_UONG { get; set; }
    }
}
